### Домашнее задание

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
X = np.array([ [   1,    1,  500,    1],
               [   1,    1,  700,    1],
               [   1,    2,  750,    2],
               [   1,    5,  600,    1],
               [   1,    3, 1450,    2],
               [   1,    0,  800,    1],
               [   1,    5, 1500,    3],
               [   1,   10, 2000,    3],
               [   1,    1,  450,    1],
               [   1,    2, 1000,    2]], dtype=np.float64)

y = np.array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1], dtype=np.float64)

In [3]:
X

array([[1.00e+00, 1.00e+00, 5.00e+02, 1.00e+00],
       [1.00e+00, 1.00e+00, 7.00e+02, 1.00e+00],
       [1.00e+00, 2.00e+00, 7.50e+02, 2.00e+00],
       [1.00e+00, 5.00e+00, 6.00e+02, 1.00e+00],
       [1.00e+00, 3.00e+00, 1.45e+03, 2.00e+00],
       [1.00e+00, 0.00e+00, 8.00e+02, 1.00e+00],
       [1.00e+00, 5.00e+00, 1.50e+03, 3.00e+00],
       [1.00e+00, 1.00e+01, 2.00e+03, 3.00e+00],
       [1.00e+00, 1.00e+00, 4.50e+02, 1.00e+00],
       [1.00e+00, 2.00e+00, 1.00e+03, 2.00e+00]])

In [4]:
y

array([0., 0., 1., 0., 1., 0., 1., 0., 1., 1.])

In [5]:
def standard_scale(x):
    res = (x - x.mean()) / x.std()
    return res

In [6]:
X_st = X.copy()
X_st[:, 2] = standard_scale(X[:, 2])

In [7]:
X_st

array([[ 1.        ,  1.        , -0.97958969,  1.        ],
       [ 1.        ,  1.        , -0.56713087,  1.        ],
       [ 1.        ,  2.        , -0.46401617,  2.        ],
       [ 1.        ,  5.        , -0.77336028,  1.        ],
       [ 1.        ,  3.        ,  0.97958969,  2.        ],
       [ 1.        ,  0.        , -0.36090146,  1.        ],
       [ 1.        ,  5.        ,  1.08270439,  3.        ],
       [ 1.        , 10.        ,  2.11385144,  3.        ],
       [ 1.        ,  1.        , -1.08270439,  1.        ],
       [ 1.        ,  2.        ,  0.05155735,  2.        ]])

In [8]:
def calc_logloss(y, y_pred):
    err = - np.mean(y * np.log(y_pred) + (1.0 - y) * np.log(1.0 - y_pred))
    return err

In [9]:
def sigmoid(z):
    res = 1 / (1 + np.exp(-z))
    return res

In [10]:
def eval_model(X, y, iterations, eta=1e-4):
    np.random.seed(42)
    W = np.random.randn(X.shape[1])
    n = X.shape[0]
#     y_predicts = []
    for i in range(iterations):
        z = np.dot(X, W)
        y_pred = sigmoid(z)
#         y_predicts.append(y_pred)
        err = calc_logloss(y, y_pred)
        
        dQ = 1/n * X.T @ (y_pred - y)
        W -= eta * dQ
        if i % (iterations / 10) == 0:
            print(i, W, err)
    return (W)

In [11]:
# Параметры модели использованные в качестве примера.
W = eval_model(X_st, y, iterations=500, eta=1e-4)
print(W)

0 [ 0.49667621 -0.13840939  0.6476858   1.52297324] 1.1785958344356262
50 [ 0.494784   -0.14564801  0.6475462   1.52014828] 1.1657985749255426
100 [ 0.49290109 -0.15285535  0.64740132  1.51733474] 1.1531112685708473
150 [ 0.49102761 -0.16003088  0.64725118  1.51453281] 1.1405352753305018
200 [ 0.48916364 -0.16717404  0.64709581  1.51174267] 1.1280719326917483
250 [ 0.48730929 -0.17428428  0.64693524  1.50896452] 1.1157225565960736
300 [ 0.48546465 -0.18136107  0.64676951  1.50619853] 1.103488442622439
350 [ 0.48362982 -0.18840385  0.64659868  1.5034449 ] 1.0913708674192037
400 [ 0.48180488 -0.19541206  0.64642281  1.50070383] 1.0793710903721336
450 [ 0.47998993 -0.20238516  0.64624195  1.49797551] 1.0674903554915993
[ 0.47822106 -0.20918419  0.64605995  1.49531432]


**2. Подберите аргументы функции eval_model для логистической регрессии таким образом, чтобы log loss был минимальным.**

In [12]:
# Параметры, при которых удалось получить минимальный показатель log loss.

In [13]:
W = eval_model(X_st, y, iterations=377000, eta=1e-1)

0 [ 0.45877546 -0.2833519   0.6449505   1.46641523] 1.1785958344356262
37700 [-21.36098662  -2.30878625  -5.5582521   17.74064702] 0.15818439792442177
75400 [-29.67764917  -3.06041094  -7.92824678  24.49004181] 0.12551071194196547
113100 [-35.40309667  -3.57560237  -9.54377388  29.11385297] 0.11027443586771982
150800 [-39.90319368  -3.97382485 -10.81401249  32.72714774] 0.1009384319878569
188500 [-43.69854148  -4.30212588 -11.89006719  35.75554739] 0.09433716601047662
226200 [-47.03967565  -4.58353157 -12.84334243  38.40407174] 0.08924791412807583
263900 [-50.06533406  -4.83099104 -13.7128289   40.78648688] 0.08509447580388904
301600 [-52.85979333  -5.05255331 -14.52187471  42.97221438] 0.08156765231973191
339300 [-55.47763708  -5.25363334 -15.28533762  45.00659342] 0.07848573851319876


<ipython-input-8-7d5907c1794a>:2: RuntimeWarning: divide by zero encountered in log
  err = - np.mean(y * np.log(y_pred) + (1.0 - y) * np.log(1.0 - y_pred))
<ipython-input-8-7d5907c1794a>:2: RuntimeWarning: invalid value encountered in multiply
  err = - np.mean(y * np.log(y_pred) + (1.0 - y) * np.log(1.0 - y_pred))


**3. Создайте функцию calc_pred_proba, возвращающую предсказанную вероятность класса 1 (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred_proba).**

In [14]:
def eval_model(X, y, iterations, eta=1e-4):
    np.random.seed(42)
    W = np.random.randn(X.shape[1])
    n = X.shape[0]
    for i in range(iterations):
        z = np.dot(X, W)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        
        dQ = 1/n * X.T @ (y_pred - y)
        W -= eta * dQ
    return (W)

In [15]:
# Для получения вероятности необходимо скалярное произведение матрицы весов и матрицы значений умножить на функцию сигмоиды:

In [16]:
def calc_pred_proba(W, X):
    z = np.dot(X, W)
    y_pred_proba = sigmoid(z)
    return y_pred_proba

In [17]:
y_pred_proba = calc_pred_proba(eval_model(X_st, y, iterations=377000, eta=1e-1), X_st)

<ipython-input-8-7d5907c1794a>:2: RuntimeWarning: divide by zero encountered in log
  err = - np.mean(y * np.log(y_pred) + (1.0 - y) * np.log(1.0 - y_pred))
<ipython-input-8-7d5907c1794a>:2: RuntimeWarning: invalid value encountered in multiply
  err = - np.mean(y * np.log(y_pred) + (1.0 - y) * np.log(1.0 - y_pred))


In [18]:
y_pred_proba

array([3.12815215e-01, 6.15960297e-04, 1.00000000e+00, 5.98475232e-12,
       9.79867333e-01, 5.18927329e-03, 1.00000000e+00, 4.39016565e-03,
       7.03535269e-01, 1.00000000e+00])

**4. Создайте функцию calc_pred, возвращающую предсказанный класс (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred).**

In [19]:
# Для получения предсказанного класса необходимо от скалярного произведения матрицы весов и матрицы значений получить знак числа,
# который покажет принадлежность к тому или другому классу.

In [20]:
def calc_pred(W, X):
    z = np.dot(X, W)
    y_pred = np.sign(z)
    return y_pred

In [21]:
y_pred = calc_pred(eval_model(X_st, y, iterations=377000, eta=1e-1), X_st)

<ipython-input-8-7d5907c1794a>:2: RuntimeWarning: divide by zero encountered in log
  err = - np.mean(y * np.log(y_pred) + (1.0 - y) * np.log(1.0 - y_pred))
<ipython-input-8-7d5907c1794a>:2: RuntimeWarning: invalid value encountered in multiply
  err = - np.mean(y * np.log(y_pred) + (1.0 - y) * np.log(1.0 - y_pred))


In [22]:
y_pred

array([-1., -1.,  1., -1.,  1., -1.,  1., -1.,  1.,  1.])

**6. Могла ли модель переобучиться? Почему?**

In [23]:
# Полагаю, что модель могла переобучиться. 
# 1. Маленькое количество данных.
# 2. Классы хорошо сбалансированы - 50/50.
# 3. Разброс значений признаков небольшой.
# Все эти факторы вместе взятые облегчают задачу для модели.